### ISSUE TITLE
咕咕咕...催更

### ISSUE THREAD

**Issue by lgyseven** [lc-hongdou/SGmiya-plugin#3]
![快干活表情包](https://user-images.githubusercontent.com/38462874/230698280-4533e803-3b0d-4361-90bd-765a9ebf2b74.jpg)

**Comment by lc-hongdou** [comment]
乐，还有人用啊

**Comment by lgyseven** [comment]
> 乐，还有人用啊

其他人不知道。我，们群有300+是等着用呢

**Comment by lc-hongdou** [comment]
> 

那我这俩天搞点进度，最近忙别的来着
