### ISSUE TITLE
日常催更，另外，部分路线图过期，无法使用

### ISSUE THREAD

**Issue by 8852690** [lc-hongdou/SGmiya-plugin#5]
FYI.

**Comment by lc-hongdou** [comment]
等明后天吧，这两天比较忙，哭死，到时候找整理一下3.6版本的路线

**Comment by 8852690** [comment]
问题不大，慢慢来（反正我是盯上你画的大饼了，不急一时）

**Comment by 8852690** [comment]
![image](https://github.com/lc-hongdou/SGmiya-plugin/assets/59615518/b88a62b4-abf8-41f1-a20f-e5ab45351fda)

**Comment by lc-hongdou** [comment]
3.7了啊，是该更新了，正好昨天比赛告一段落_(:з」∠)_别急

**Comment by 8852690** [comment]
![image](https://github.com/lc-hongdou/SGmiya-plugin/assets/59615518/19d7258f-e2db-4689-954c-254c448941b4)
算了，就不催了，躺平~
